drop table if exists film, users, mpa, film_mpa, genre, film_genre, likes, friend;

create table if not exists mpa (
    id int primary key,
    name varchar(50)
);

create table if not exists genre (
    id int primary key,
    name varchar(50)
);

create table if not exists film (
    id int generated by default as identity primary key,
    name varchar,
    description varchar(200),
    release_date date,
    duration int
);

create table if not exists users (
    id int generated by default as identity primary key,
    email varchar,
    login varchar,
    birthday date,
    name varchar
);

create table if not exists film_genre (
    film_id int references film (id),
    genre_id int references genre (id)
);

create table if not exists film_mpa (
    film_id int primary key,
    mpa_id int references mpa (id)
);

create table if not exists friend (
    user_id int references users (id),
    friend_id int references users (id),
    friend_status int,
    constraint friend_pk primary key (user_id, friend_id)
);

create table if not exists likes (
    film_id int references film (id),
    user_id int references users (id),
    constraint likes_pk primary key (film_id, user_id)
);