drop table if exists film, `user`, mpa, film_mpa, genre, film_genre, `like`, friend;

create table if not exists mpa (
    id int primary key,
    name varchar(5)
);

create table if not exists genre (
    id int primary key,
    name varchar(14)
);

create table if not exists film (
    id int generated by default as identity primary key,
    name varchar,
    description varchar(200),
    release_date date,
    duration int
);

create table if not exists `user` (
    id int generated by default as identity primary key,
    email varchar,
    login varchar,
    birthday date,
    name varchar
);

create table if not exists film_genre (
    film_id int primary key references film (id),
    genre_id int references genre (id)
);

create table if not exists film_mpa (
    film_id int primary key,
    mpa_id int references mpa (id)
);

create table if not exists friend (
    user_id int references `user` (id),
    friend_id int references `user` (id),
    friend_status int,
    constraint friend_pk primary key (user_id, friend_id)
);

create table if not exists `like` (
    film_id int references film (id),
    user_id int references `user` (id),
    constraint like_pk primary key (film_id, user_id)
);